site_name: Vocasync Studios
site_url: https://wiki.retailbridge/vocasync
nav:
  - Home: index.md
  - VocaSync:
      - Overview: vocasync/project_overview.md
      - Architecture: vocasync/architecture.md
  - Phases:
      - MVP Phase (Phase 1):
          - Overview: phases/phase1_mvp/index.md
          - Speech to Text: phases/phase1_mvp/speech_to_text.md
          - Translation: phases/phase1_mvp/translation.md
          - Emotion Detection: phases/phase1_mvp/emotion_detection.md
          - Voice Synthesis: phases/phase1_mvp/voice_synthesis.md
          - Lip Sync: phases/phase1_mvp/lip_sync.md
          - Manual Pipeline Integration: phases/phase1_mvp/manual_pipeline.md
      - Alpha Phase (Phase 2): phases/phase2_alpha/index.md
  - Glossary: glossary.md
theme:
  features:
    - navigation.footer
  icon:
    logo: fontawesome/solid/w
  name: material
  
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist
  
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com

copyright: Copyright &copy; 2025 RetailBridge LLC